/* Copyright (c) 2011 The WebM project authors. All Rights Reserved. */
/*  */
/* Use of this source code is governed by a BSD-style license */
/* that can be found in the LICENSE file in the root of the source */
/* tree. An additional intellectual property rights grant can be found */
/* in the file PATENTS.  All contributing project authors may */
/* be found in the AUTHORS file in the root of the source tree. */
/* This file automatically generated by configure. Do not edit! */
#ifndef VPX_CONFIG_H
#define VPX_CONFIG_H
#define RESTRICT    
#define INLINE      inline
#define VPX_ARCH_ARM 1
#define VPX_ARCH_AARCH64 0
#define VPX_ARCH_MIPS 0
#define VPX_ARCH_X86 0
#define VPX_ARCH_X86_64 0
#define VPX_ARCH_PPC 0
#define VPX_ARCH_LOONGARCH 0
/* Varan: Win-ARM is NEON-off (aligns with the tree's HAVE_ARM_NEON='').
   NEON intrinsics crash the LLVM ARM CodeView emitter under -Zi and NEON .asm is A32
   (forbidden on Win RT). Keep C-only here + drop the NEON sources in moz.build. Real
   Linux/arm (which also reads this config) keeps NEON. */
#if defined(_WIN32)
/* Varan v1.1: HAVE_NEON_ASM stays 0 -- libvpx's ARM .asm is A32 and is
   dialect-forbidden on Windows RT. But HAVE_NEON is now 1: the _neon.c files are C
   INTRINSICS, which clang-cl compiles to Thumb-2 NEON, exactly as M4.2 already shipped
   for libpng / libjpeg-turbo / libwebp (measured 18% / 26% / 33% faster, pixel-exact).
   MEASURED 2026-09-15 before flipping this: of 97 _neon.c files, 73 compile clean with
   -Zi and ZERO produce the "unknown codeview register" ICE that this block previously
   cited as the reason for disabling them. Of the 24 that fail, 12 are highbd, 8 are
   ARMv8.2-only (dotprod/i8mm) and 3 are encoder-side; the single decode-relevant failure
   (vpx_convolve_neon.c) fails ONLY because HAVE_NEON=0 removes its rtcd declarations,
   i.e. it is a consequence of this flag, not a cause. */
#define HAVE_NEON_ASM 0
#define HAVE_NEON 1
#else
#define HAVE_NEON_ASM 1
#define HAVE_NEON 1
#endif
#define HAVE_NEON_DOTPROD 0
#define HAVE_NEON_I8MM 0
#define HAVE_SVE 0
#define HAVE_SVE2 0
#define HAVE_MIPS32 0
#define HAVE_DSPR2 0
#define HAVE_MSA 0
#define HAVE_MIPS64 0
#define HAVE_MMX 0
#define HAVE_SSE 0
#define HAVE_SSE2 0
#define HAVE_SSE3 0
#define HAVE_SSSE3 0
#define HAVE_SSE4_1 0
#define HAVE_AVX 0
#define HAVE_AVX2 0
#define HAVE_AVX512 0
#define HAVE_VSX 0
#define HAVE_MMI 0
#define HAVE_LSX 0
#define HAVE_LASX 0
#define HAVE_VPX_PORTS 1
/* Varan: Win-ARM has no <pthread.h>/<semaphore.h>. Force libvpx's
   built-in Win32 SRWLOCK/HANDLE/CONDITION_VARIABLE emulation (vpx_util/vpx_pthread.h
   L23; vp8/common/threading.h L22 falls to the <windows.h> path when !HAVE_PTHREAD_H).
   We only ever build win-arm from this linux/arm config; real Linux/arm keeps pthreads. */
#if defined(_WIN32)
#define HAVE_PTHREAD_H 0
#else
#define HAVE_PTHREAD_H 1
#endif
#define CONFIG_DEPENDENCY_TRACKING 1
#define CONFIG_EXTERNAL_BUILD 1
#define CONFIG_INSTALL_DOCS 0
#define CONFIG_INSTALL_BINS 1
#define CONFIG_INSTALL_LIBS 1
#define CONFIG_INSTALL_SRCS 0
#define CONFIG_DEBUG 0
#define CONFIG_GPROF 0
#define CONFIG_GCOV 0
#define CONFIG_RVCT 0
#define CONFIG_GCC 1
#define CONFIG_MSVS 0
#define CONFIG_PIC 1
#define CONFIG_BIG_ENDIAN 0
#define CONFIG_CODEC_SRCS 0
#define CONFIG_DEBUG_LIBS 0
#define CONFIG_DEQUANT_TOKENS 0
#define CONFIG_DC_RECON 0
/* Varan: Win-ARM uses static (C) dispatch -- no runtime CPU probe. This
   also removes the SEH __try feature-probe in vpx_ports/aarch32_cpudetect.c (clang-cl
   can't lower __try on thumbv7). Real Linux/arm keeps runtime detection. */
#if defined(_WIN32)
#define CONFIG_RUNTIME_CPU_DETECT 0
#else
#define CONFIG_RUNTIME_CPU_DETECT 1
#endif
#define CONFIG_POSTPROC 0
#define CONFIG_VP9_POSTPROC 0
#define CONFIG_MULTITHREAD 1
#define CONFIG_INTERNAL_STATS 0
#define CONFIG_VP8_ENCODER 1
#define CONFIG_VP8_DECODER 1
#define CONFIG_VP9_ENCODER 1
#define CONFIG_VP9_DECODER 1
#define CONFIG_VP8 1
#define CONFIG_VP9 1
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1
#define CONFIG_STATIC_MSVCRT 0
#define CONFIG_SPATIAL_RESAMPLING 1
#define CONFIG_REALTIME_ONLY 1
#define CONFIG_ONTHEFLY_BITPACKING 0
#define CONFIG_ERROR_CONCEALMENT 0
#define CONFIG_SHARED 0
#define CONFIG_STATIC 1
#define CONFIG_SMALL 0
#define CONFIG_POSTPROC_VISUALIZER 0
#define CONFIG_OS_SUPPORT 1
#define CONFIG_UNIT_TESTS 0
#define CONFIG_WEBM_IO 1
#define CONFIG_LIBYUV 1
#define CONFIG_DECODE_PERF_TESTS 0
#define CONFIG_ENCODE_PERF_TESTS 0
#define CONFIG_MULTI_RES_ENCODING 1
#define CONFIG_TEMPORAL_DENOISING 1
#define CONFIG_VP9_TEMPORAL_DENOISING 0
#define CONFIG_COEFFICIENT_RANGE_CHECKING 0
#define CONFIG_VP9_HIGHBITDEPTH 0
#define CONFIG_BETTER_HW_COMPATIBILITY 0
#define CONFIG_EXPERIMENTAL 0
#define CONFIG_SIZE_LIMIT 1
#define CONFIG_ALWAYS_ADJUST_BPM 0
#define CONFIG_BITSTREAM_DEBUG 0
#define CONFIG_MISMATCH_DEBUG 0
#define CONFIG_FP_MB_STATS 0
#define CONFIG_EMULATE_HARDWARE 0
#define CONFIG_NON_GREEDY_MV 0
#define CONFIG_COLLECT_COMPONENT_TIMING 0
#define DECODE_WIDTH_LIMIT 8192
#define DECODE_HEIGHT_LIMIT 4608
#endif /* VPX_CONFIG_H */
